In [2]:
import pandas as pd
import json

In [ ]:
from pymongo.mongo_client import MongoClient

In [ ]:
#url
url = "mongodb+srv://guptadaizy2495_db_user:Qphv1NNe5PveUHrE@cluster0.q2qligt.mongodb.net/?appName=Cluster0"

In [5]:
client = MongoClient(url)

In [6]:
DATABASE_NAME = "waferData"
COLLECTION_NAME = "sampleWafer"

In [7]:
df = pd.read_csv('notebooks\wafer_23012020_041211.csv')

In [8]:
df.head()

,Unnamed: 0,Sensor-1,Sensor-2,Sensor-3,Sensor-4,Sensor-5,Sensor-6,Sensor-7,Sensor-8,Sensor-9,...,Sensor-582,Sensor-583,Sensor-584,Sensor-585,Sensor-586,Sensor-587,Sensor-588,Sensor-589,Sensor-590,Good/Bad
0,Wafer-801,2968.33,2476.58,2216.7333,1748.0885,1.1127,100.0,97.5822,0.1242,1.5300,...,NaN,0.5004,0.0120,0.0033,2.4069,0.0545,0.0184,0.0055,33.7876,-1
1,Wafer-802,2961.04,2506.43,2170.0666,1364.5157,1.5447,100.0,96.7700,0.1230,1.3953,...,NaN,0.4994,0.0115,0.0031,2.3020,0.0545,0.0184,0.0055,33.7876,1
2,Wafer-803,3072.03,2500.68,2205.7445,1363.1048,1.0518,100.0,101.8644,0.1220,1.3896,...,NaN,0.4987,0.0118,0.0036,2.3719,0.0545,0.0184,0.0055,33.7876,-1
3,Wafer-804,3021.83,2419.83,2205.7445,1363.1048,1.0518,100.0,101.8644,0.1220,1.4108,...,NaN,0.4934,0.0123,0.0040,2.4923,0.0545,0.0184,0.0055,33.7876,-1
4,Wafer-805,3006.95,2435.34,2189.8111,1084.6502,1.1993,100.0,104.8856,0.1234,1.5094,...,NaN,0.4987,0.0145,0.0041,2.8991,0.0545,0.0184,0.0055,33.7876,-1

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Columns: 592 entries, Unnamed: 0 to Good/Bad
dtypes: float64(494), int64(97), object(1)
memory usage: 462.6+ KB

In [10]:
df.isnull().sum()

Unnamed: 0    0
Sensor-1      1
Sensor-2      0
Sensor-3      3
Sensor-4      3
             ..
Sensor-587    0
Sensor-588    0
Sensor-589    0
Sensor-590    0
Good/Bad      0
Length: 592, dtype: int64

In [12]:
# df[df.isnull().sum()]
df.loc[:,df.isnull().sum()>0]

,Sensor-1,Sensor-3,Sensor-4,Sensor-5,Sensor-6,Sensor-7,Sensor-8,Sensor-41,Sensor-42,Sensor-54,...,Sensor-565,Sensor-566,Sensor-567,Sensor-568,Sensor-569,Sensor-570,Sensor-579,Sensor-580,Sensor-581,Sensor-582
0,2968.33,2216.7333,1748.0885,1.1127,100.0,97.5822,0.1242,79.71,2.849,4.549,...,5.18,0.2259,2.0235,0.0886,1.9520,31.5069,NaN,NaN,NaN,NaN
1,2961.04,2170.0666,1364.5157,1.5447,100.0,96.7700,0.1230,79.31,3.331,NaN,...,4.98,0.0877,2.0902,0.0382,1.8844,15.4662,NaN,NaN,NaN,NaN
2,3072.03,2205.7445,1363.1048,1.0518,100.0,101.8644,0.1220,80.57,3.675,4.610,...,11.18,0.1832,4.2535,0.0714,4.2029,20.9204,NaN,NaN,NaN,NaN
3,3021.83,2205.7445,1363.1048,1.0518,100.0,101.8644,0.1220,79.38,2.951,4.549,...,4.98,0.0877,2.0902,0.0382,1.8844,15.4662,NaN,NaN,NaN,NaN
4,3006.95,2189.8111,1084.6502,1.1993,100.0,104.8856,0.1234,79.05,3.395,4.590,...,4.98,0.0877,2.0902,0.0382,1.8844,15.4662,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,3013.66,2185.2111,1141.6306,0.8447,100.0,100.5978,0.1217,79.94,3.054,4.569,...,4.98,0.0877,2.0902,0.0382,1.8844,15.4662,NaN,NaN,NaN,NaN
96,2982.87,2315.2667,2360.1325,1.1259,100.0,90.1144,0.1160,79.86,2.936,4.603,...,4.98,0.0877,2.0902,0.0382,1.8844,15.4662,NaN,NaN,NaN,NaN
97,3084.82,2171.5000,1028.4440,0.7899,100.0,101.5122,0.1224,80.18,2.970,4.619,...,4.98,0.0877,2.0902,0.0382,1.8844,15.4662,NaN,NaN,NaN,NaN
98,2955.87,NaN,NaN,NaN,NaN,NaN,NaN,12.19,4.886,4.610,...,6.00,0.4698,2.2119,0.1792,2.2956,57.3738,NaN,NaN,NaN,NaN
99,2914.86,2210.2778,2120.5760,1.0700,100.0,95.1089,0.1230,79.86,2.936,4.603,...,4.98,0.0877,2.0902,0.0382,1.8844,15.4662,NaN,NaN,NaN,NaN

In [13]:
df.columns[df.isnull().sum() > 0]

Index(['Sensor-1', 'Sensor-3', 'Sensor-4', 'Sensor-5', 'Sensor-6', 'Sensor-7',
       'Sensor-8', 'Sensor-41', 'Sensor-42', 'Sensor-54',
       ...
       'Sensor-565', 'Sensor-566', 'Sensor-567', 'Sensor-568', 'Sensor-569',
       'Sensor-570', 'Sensor-579', 'Sensor-580', 'Sensor-581', 'Sensor-582'],
      dtype='object', length=167)

In [14]:
null_columns = df.isnull().sum()
null_columns = null_columns[null_columns > 0]
print(null_columns)

Sensor-1       1
Sensor-3       3
Sensor-4       3
Sensor-5       3
Sensor-6       3
              ..
Sensor-570     3
Sensor-579    66
Sensor-580    66
Sensor-581    66
Sensor-582    66
Length: 167, dtype: int64

In [18]:
df.isnull().mean()

Unnamed: 0    0.00
Sensor-1      0.01
Sensor-2      0.00
Sensor-3      0.03
Sensor-4      0.03
              ...
Sensor-587    0.00
Sensor-588    0.00
Sensor-589    0.00
Sensor-590    0.00
Good/Bad      0.00
Length: 592, dtype: float64

In [19]:
threshold = 0.7
null_percent = df.isnull().mean()
null_cols = null_percent[null_percent>threshold]
print(null_cols)

Sensor-158    0.91
Sensor-159    0.91
Sensor-293    0.91
Sensor-294    0.91
dtype: float64

In [23]:
row_null_percentage = df.isnull().mean(axis=1)
high_null_rows = df[row_null_percentage > 0.7]
print(high_null_rows)

Empty DataFrame
Columns: [Unnamed: 0, Sensor-1, Sensor-2, Sensor-3, Sensor-4, Sensor-5, Sensor-6, Sensor-7, Sensor-8, Sensor-9, Sensor-10, Sensor-11, Sensor-12, Sensor-13, Sensor-14, Sensor-15, Sensor-16, Sensor-17, Sensor-18, Sensor-19, Sensor-20, Sensor-21, Sensor-22, Sensor-23, Sensor-24, Sensor-25, Sensor-26, Sensor-27, Sensor-28, Sensor-29, Sensor-30, Sensor-31, Sensor-32, Sensor-33, Sensor-34, Sensor-35, Sensor-36, Sensor-37, Sensor-38, Sensor-39, Sensor-40, Sensor-41, Sensor-42, Sensor-43, Sensor-44, Sensor-45, Sensor-46, Sensor-47, Sensor-48, Sensor-49, Sensor-50, Sensor-51, Sensor-52, Sensor-53, Sensor-54, Sensor-55, Sensor-56, Sensor-57, Sensor-58, Sensor-59, Sensor-60, Sensor-61, Sensor-62, Sensor-63, Sensor-64, Sensor-65, Sensor-66, Sensor-67, Sensor-68, Sensor-69, Sensor-70, Sensor-71, Sensor-72, Sensor-73, Sensor-74, Sensor-75, Sensor-76, Sensor-77, Sensor-78, Sensor-79, Sensor-80, Sensor-81, Sensor-82, Sensor-83, Sensor-84, Sensor-85, Sensor-86, Sensor-87, Sensor-88, Sensor-89, Sensor-90, Sensor-91, Sensor-92, Sensor-93, Sensor-94, Sensor-95, Sensor-96, Sensor-97, Sensor-98, Sensor-99, ...]
Index: []

[0 rows x 592 columns]

In [24]:
df.columns

Index(['Unnamed: 0', 'Sensor-1', 'Sensor-2', 'Sensor-3', 'Sensor-4',
       'Sensor-5', 'Sensor-6', 'Sensor-7', 'Sensor-8', 'Sensor-9',
       ...
       'Sensor-582', 'Sensor-583', 'Sensor-584', 'Sensor-585', 'Sensor-586',
       'Sensor-587', 'Sensor-588', 'Sensor-589', 'Sensor-590', 'Good/Bad'],
      dtype='object', length=592)

In [27]:
df['Good/Bad'].value_counts(normalize=True)*100

Good/Bad
-1    94.0
 1     6.0
Name: proportion, dtype: float64

imbalance dataset

In [28]:
df = df.drop('Unnamed: 0', axis=1)

In [29]:
df.columns

Index(['Sensor-1', 'Sensor-2', 'Sensor-3', 'Sensor-4', 'Sensor-5', 'Sensor-6',
       'Sensor-7', 'Sensor-8', 'Sensor-9', 'Sensor-10',
       ...
       'Sensor-582', 'Sensor-583', 'Sensor-584', 'Sensor-585', 'Sensor-586',
       'Sensor-587', 'Sensor-588', 'Sensor-589', 'Sensor-590', 'Good/Bad'],
      dtype='object', length=591)

In [30]:
json_record = list(json.loads(df.T.to_json()).values())

In [31]:
client[DATABASE_NAME][COLLECTION_NAME].insert_many(json_record)